import javax.swing.JOptionPane;

public class Guessing_Game {

	public static void main(String[] args) {

		// A variable that controls whether the program will run or not
		Boolean run = true;
		// This "do" statement holds the whole game
		do {
			// The players enters their name
			String name1 = JOptionPane.showInputDialog("First Player Name:");
			String name2 = JOptionPane.showInputDialog("Second Player Name:");

			// The computer choose 3 numbers
			int rand1 = 1 + (int) (Math.random() * 5);
			int rand2 = 1 + (int) (Math.random() * 5);
			int rand3 = 1 + (int) (Math.random() * 5);

			// This "Boolean" variable tells us whether the 3 numbers are different or not
			Boolean isDif = false;

			/*
			 * This "while" loop is checking whether the 3 numbers are different or not if
			 * not, the computer will choose different numbers until we will achieve
			 * variability
			 */
			while (!isDif) {
				if (rand1 == rand2 || rand1 == rand3) {
					rand1 = 1 + (int) (Math.random() * 5);
				} else if (rand2 == rand3) {
					rand2 = 1 + (int) (Math.random() * 5);
				} else {
					isDif = true;
				}
			}

			// This "Boolean" variable tells us whether the game will run in practice mode
			// or not
			Boolean isPrac = true;
			// This "String" variable is holding the choice of the user for the practice
			// mode
			String practice = "";
			// The user choose in which mode to run the game
			practice = JOptionPane.showInputDialog("For practice:\n" + "How many secret numbers do you want to show?\n"
					+ "Press: 1,2,3 or Cancel for none");
			/*
			 * This "while" loop will take the user choice and apply it. if the user chose
			 * to run the game in practice mode, the loop will write the appropriate number
			 * of variables in the console
			 */
			while (isPrac) {
				if (practice != null) {
					if (!practice.equals("1") & !practice.equals("2") & !practice.equals("3")) {
						practice = JOptionPane.showInputDialog("You entered a wrong character.\n" + "For practice:\n"
								+ "How many secret numbers do you want to show?\n" + "Press: 1,2,3 or Cancel for none");
					} else {
						switch (practice) {
						case "1":
							System.out.println(rand1);
							break;
						case "2":
							System.out.println(rand1 + " , " + rand2);
							break;
						case "3":
							System.out.println(rand1 + " , " + rand2 + " , " + rand3);
							break;
						}
						isPrac = false;
					}
				} else {
					isPrac = false;
				}
			}

			// This "Integer" variables hold the numbers guessed by the players
			int guess1 = 0;
			int guess2 = 0;
			int guess3 = 0;
			// This "Integer" variable holds a counting of the correct guesses made by the
			// players
			int counter = 0;
			// This "Integer" variable holds the response of the user the whether he wants
			// to begin a new game or not
			int response = 0;
			// This "Boolean" variable tells us whether a player won or not
			Boolean won = false;
			// This "Integer" variable tells us whose turn is it next
			int turn = 1;
			// This "String" variable tells us what is the name of the current player
			String name = name1;
			// This "while" loop is holding the actual game. It will run until one of the
			// players will win

			while (!won) {
				counter = 0;
				// The first player is inserting his guesses
				guess1 = Integer.parseInt(JOptionPane
						.showInputDialog("Player #" + turn + ", " + name + "\nPlease enter your first guess"));
				guess2 = Integer.parseInt(JOptionPane
						.showInputDialog("Player #" + turn + ", " + name + "\nPlease enter your second guess"));
				while (guess1 == guess2) {
					guess2 = Integer.parseInt(JOptionPane.showInputDialog("Player #" + turn + ", " + name
							+ "\nYou need to enter three different guesses\nPlease enter another guess"));
				}
				guess3 = Integer.parseInt(JOptionPane
						.showInputDialog("Player #" + turn + ", " + name + "\nPlease enter your third guess"));
				while (guess1 == guess3 || guess2 == guess3) {
					guess3 = Integer.parseInt(JOptionPane.showInputDialog("Player #" + turn + ", " + name
							+ "\nYou need to enter three different guesses\nPlease enter another guess"));
				}

				/*
				 * These "if" statements will check whether the numbers guessed by the player
				 * are identical to the numbers generated by the computer
				 */
				if (guess1 == rand1 || guess1 == rand2 || guess1 == rand3) {
					counter++;
				}
				if (guess2 == rand1 || guess2 == rand2 || guess2 == rand3) {
					counter++;
				}
				if (guess3 == rand1 || guess3 == rand2 || guess3 == rand3) {
					counter++;
				}

				/*
				 * This "if" statement is checking whether the player won or not. If the player
				 * didn't win, the computer will write the number of correct guesses. If the
				 * player won, the computer will ask if the user want to play a new game
				 */
				if (counter != 3) {
					JOptionPane.showMessageDialog(null,
							counter + " number" + (counter > 1 ? "s were" : " was") + " guessed correctly");
				} else {
					response = JOptionPane.showConfirmDialog(null, "Congragulations!\nPlayer #" + turn + ", " + name
							+ " won!\nDo you want to start a new game?");
					won = true;
				}
				if (!won) {
					switch (turn) {
					case 1:
						turn = 2;
						name = name2;
						break;
					case 2:
						turn = 1;
						name = name1;
						break;
					}
				}
			}

			/*
			 * This "if" statement takes the user choice in respect of the game initiation
			 * and apply it. If the player chose to initiate the game, the game will start
			 * again. If the player chose to end the game, the loop will end
			 */
			if (response != 0) {
				run = false;
			}

		} while (run);

		// A massage in regard of the ending of the game will appear
		JOptionPane.showMessageDialog(null, "The End");
	}
}
